version: '3.5'

services:
  wiz:
    container_name: wiz
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        nowDate: $NOWDATE
    volumes:
      - './src:/src/app'
    expose:
      - '80'
    ports:
      - '8080:80'
